### ISSUE TITLE
Error with example code

### ISSUE THREAD

**Issue by Arkangel12** [lpongetti/flutter_map_marker_cluster#1]
Hello, 

i saw the example code and the video made with this and i think its an amazing feature so i try it in my current code, I just  adde the MarkerClusterGroupLayerOptions and add my markers the i have in MarkerLayerOptions but it send and error as soon as i change it . 

i will let you the error screen so you see the error and another one with the error message.

*Note: currently i have everything working I just add this because it could be an amazing feature 👍 hope you can solve this so i can try it.

![Console error](https://user-images.githubusercontent.com/29683014/59533741-3fa27100-8ea1-11e9-95c4-9220b28c5768.png)
![App Screenshot](https://user-images.githubusercontent.com/29683014/59533742-3fa27100-8ea1-11e9-895f-bb0dd25e1ac0.png)

**Comment by lpongetti** [comment]
you have to insert into plugins the MarkerClusterGroupPlugin class

```
options: new MapOptions(
        zoom: 2,
        plugins: [
          MarkerClusterGroupPlugin(),
        ],
      ),
```

**Comment by Arkangel12** [comment]
🤦‍♂  so dump! i went straight to the markers, thanks man!
