### ISSUE TITLE
The clustering marker is not disclosed

### ISSUE THREAD

**Issue by Vafin84** [lpongetti/flutter_map_marker_cluster#102]
Hello. I am faced with a problem of the following nature. When I click on the clustering marker, it does not expand (does not show the markers it contains) . I believe this behavior occurs when the child marker is on the boundary of the clustering radius

![Juj5e7I1t9](https://user-images.githubusercontent.com/49650802/143481824-c1119390-c4a9-4d90-9def-788b612a7d79.gif)

**Comment by lpongetti** [comment]
hi, thanks for reporting, i will investigate the cause

**Comment by lpongetti** [comment]
Pls check fitBoundsOptions, you can set the maxZoom when fit bounds. In your case you have to set the same value of MapOptions.maxZoom

fitBoundsOptions: FitBoundsOptions(
  maxZoom: 20,
  padding: EdgeInsets.all(50),
),

**Comment by Vafin84** [comment]
> Pls check fitBoundsOptions, you can set the maxZoom when fit bounds. In your case you have to set the same value of MapOptions.maxZoom
> 
> fitBoundsOptions: FitBoundsOptions( maxZoom: 20, padding: EdgeInsets.all(50), ),

Thank you very much! It really helped, now the clustering marker works flawlessly.  I think you can close Issue
