### ISSUE TITLE
Popupbuilder custom marker

### ISSUE THREAD

**Issue by berkayoruc** [lpongetti/flutter_map_marker_cluster#103]
Hi, first of all thank you for the awesome package. Question is simple. As I mentioned at title, is using custom marker widget instead of default marker possible? I want to show some custom attributes on popup container.

Default popupbuilder:
`
popupBuilder: (BuildContext context, Marker marker) {
`

What I want:
`
popupBuilder: (BuildContext context, FacilityMarker marker) {
`

FacilityMarker is like;
```
class FacilityMarker extends Marker {
  final String name;
  final String address;
  final String poiID;

  FacilityMarker(
      {required LatLng point,
      required WidgetBuilder builder,
      double width = 30,
      double height = 30,
      required AnchorPos anchorPos,
      required this.name,
      required this.address,
      required this.poiID})
      : super(
            point: point, builder: builder, width: width, anchorPos: anchorPos);
}
```

**Comment by lpongetti** [comment]
you can do this

popupBuilder: (context, marker) {
                    final facilityMarker = marker as FacilityMarker;

**Comment by berkayoruc** [comment]
@lpongetti oh🙄 Thank you, I should work flutter more😄
