### ISSUE TITLE
Cluster break animation(fade out+scale down) and Cluster create animation(fade in+scale up)

### ISSUE THREAD

**Issue by aytunch** [lpongetti/flutter_map_marker_cluster#11]
Also for the single Markers; a location tween from/to between a cluster would be perfect.

**Comment by Mkohm** [comment]
It breaks animation for me as well, and unfortunately makes this package unusable for me. Any input on how we can fix this?

**Comment by Mkohm** [comment]
Some additional information: I am using a bottomsheet with (Scaffold.of(context).showBottomsheet()) and when i use this library it will not animate anymore. How could i know if this library will interfere with the bottomsheet animation?

**Comment by Mkohm** [comment]
Is it fixed?
