### ISSUE TITLE
Markers getting rebuilt and losing state after click

### ISSUE THREAD

**Issue by stx** [lpongetti/flutter_map_marker_cluster#114]
Thank you for this amazing plugin! You've done a great job.

On the web, we have markers that animate on click.

The state for these markers are getting reset on click (a new hashCode ID is generated) and thus messing up the animations. This is happening even when a key is provided to MarkerClusterLayerWidget, the Marker widget and the animated widget underneath it.

When moving the markers from MarkerClusterLayerWidget to the standard MarkerLayerWidget, the problem disappears.

**Comment by rafallezanko** [comment]
Hi!
I have meet same issue. Do you have plans to solve that?

Thanks!

**Comment by rafallezanko** [comment]
I think I have solved my issue.

@stx , do you pass popupController?

I had to add to MapOptions:
            onTap: (tapPosition, latLng) =>
                _popupLayerController.hideAllPopups(),

And that to MarkerClusterLayerOptions.popupOptions:
                popupController: _popupLayerController,
