### ISSUE TITLE
New markers are not loading, 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [lpongetti/flutter_map_marker_cluster#115]
Hello There, 

Thank you for such a nice plugin, I am using StreamBuilder and when ever new data is loaded from the backend, I create set of markers (Marker objects) and then provide to this plugin. Problem is new markers are not loading, even i tried to run SetState() as well. Any solution or work around to make it properly functional? This plugin is very important for us. 

https://user-images.githubusercontent.com/8264639/164356431-af4cc528-a1eb-4032-b7b5-1346717d9fb6.mov

**Comment by ch-muhammad-adil** [comment]
If all markers are provided at first load everything works fine, for example here I loaded all markers and then enabled this plugin. 


https://user-images.githubusercontent.com/8264639/164356972-953ee3a2-c1eb-424b-b091-7031d67d91fc.mov

**Comment by derqurps** [comment]
I too happen to have the same problem that my markers are loaded asynchronously and are not showing in the cluster map. In contrast if i put my markers in a MarkerLayerWidget it does work. But then the clustering does not work.

**Comment by ch-muhammad-adil** [comment]
Were you able to fix this problem?

**Comment by derqurps** [comment]
No unfortunately not. I am currently trying to circumvent the problem and load everything ahead of time.

**Comment by ch-muhammad-adil** [comment]
Which is not a good solution.

**Comment by rorystephenson** [comment]
I've had a similar problem before and from memory it was because if the List instance doesn't change then the clustering code things that the markers haven't changed. So when you change the list of markers try something like:

```dart
setState((){
  _markers.addAll(yourNewMarkers);
  _markers = List.from(_markers);
});
```

**Comment by ch-muhammad-adil** [comment]
Thanks it has fixed the problem @rorystephenson 

I was using stream of markers and all i have done is 

List.from(snapshot.data).

**Comment by blablabla123-cell** [comment]
Thank you for the solution. Helpe immediately!
