### ISSUE TITLE
Is it possible to create for the web?

### ISSUE THREAD

**Issue by hoseinmoradi** [lpongetti/flutter_map_marker_cluster#122]
I need to use a cluster for a web project using Open Street Map.
 Is it possible to support the web?

**Comment by Vafin84** [comment]
> I need to use a cluster for a web project using Open Street Map. Is it possible to support the web?

The plugin supports the web
![image](https://user-images.githubusercontent.com/49650802/176410302-95a13f8f-73f6-424d-bfe1-4dc4d4c71844.png)
