### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by aytunch** [lpongetti/flutter_map_marker_cluster#124]
This happens sometimes and especially when I try to **pinch&zoom**. And the error goes away once we pan the map.

Also when the user presses on the permission button and the OS presents the location permission dialog, this error gets triggered more often.
The video is from a release build. In the debug build, we get the red error screen all over the map. And after a hot restart, the error goes away (cmd+s)

**Notes: the cat marker is not part of a cluster marker. It lives at the last layer, above the cluster marker layers. And as you can see, it renders correctly
The moment I remove `MarkerClusterLayerOptions` from the code, error does not happen.**

Has anyone came across with this problem before? 
@lpongetti if you have some time and have any leads, I would be glad to help solve this issue along with you. Thanks for this awesome plugin.

EDIT: 
Line 200 is the problematic line as the debugger shows. 

Seems like we use the `_clusterManager.spiderfyCluster!.markers` while `spiderfyCluster` is null. Would a simple `spiderfyCluster != null` check fix this?

<img width="786" alt="Screen Shot 2022-07-10 at 01 51 59" src="https://user-images.githubusercontent.com/6442915/178125121-5f42dcb2-a74d-4c2b-8d82-00aa15d3938d.png">

https://user-images.githubusercontent.com/6442915/178124885-1970892d-e3fe-4a75-b4c5-a0f3fbd061bd.mov

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-07-10 at 01 37 32](https://user-images.githubusercontent.com/6442915/178124782-efd08f15-f2b0-4921-bf36-1a63cf1ceb00.png)

<img width="1251" alt="Screen Shot 2022-07-10 at 01 28 38" src="https://user-images.githubusercontent.com/6442915/178124677-08678b6f-7eb0-4964-b915-b77b40cdaf9f.png">
<img width="502" alt="Screen Shot 2022-07-10 at 01 28 12" src="https://user-images.githubusercontent.com/6442915/178124678-6ae3e5d3-6957-421d-b095-9b3c9f46e409.png">

<img width="1282" alt="Screen Shot 2022-07-11 at 22 03 19" src="https://user-images.githubusercontent.com/6442915/178358912-87acbdb2-5860-4008-98d9-9f21eaec0b5d.png">

**Comment by aytunch** [comment]
@rbellens Hi, I saw your PR https://github.com/lpongetti/flutter_map_marker_cluster/pull/125
Do you think it solves this issue as well?
Thanks.

**Comment by rbellens** [comment]
don't think it is related.

**Comment by pfraunlob** [comment]
Also having this issue

**Comment by ch-muhammad-adil** [comment]
Same problem.. Please fix....

**Comment by aytunch** [comment]
Temporarily, you can use my Fork. I made several bug fixes in the Branch and made it so that you can use flutter_map 2.0.0

```
  flutter_map: ^2.0.0
  flutter_map_marker_cluster:
    git:
      url: https://github.com/aytunch/flutter_map_marker_cluster
```

**Comment by TitanKing** [comment]
> 

Hi @aytunch, do you perhaps have a branch with all the fixes? I do not think the maintainer of the project have much time for this anymore.

**Comment by aytunch** [comment]
@TitanKing I shared my fork above: https://github.com/aytunch/flutter_map_marker_cluster
The reason I am not opening a PR is because `flutter_map_marker_popup`s maintainer has not updated his package.
In order to support `flutter_map: ^2.0.0`, I had to use someone's flutter_map_marker_popup fork.
And for publishable packages it does not allow to have forks in the pubspec.yaml.
