### ISSUE TITLE
Map is not updated after markers added dynamically

### ISSUE THREAD

**Issue by kevinZartek** [lpongetti/flutter_map_marker_cluster#137]
I am using riverpod change notifier as a view model for the flutter map, but the map always display the initial set of markers. Any change in this list of markers is not reflected in map. I have debugged the code and list itself is updated but map UI is not.

**Comment by kamami** [comment]
Same issue here. The markers are not updated in the map, when changed in the array. Without clustering it is working as expected.

**Comment by blablabla123-cell** [comment]
Same issue, did anyone fix it?

**Comment by blablabla123-cell** [comment]
I found the solution. In the markerClusterLayerWidget instead of passing just markers to the markers propetry, use List.from(markers), so you create a new instance of a list with markers and it work's perfectly fine!

**Comment by Apollo108** [comment]
Well, not perfectly fine. It redraws markers, indeed, but it doesn't maintain it's state. In fact, when a cluster is spiderfied (open), and update happens, it collapses back, which makes it unusable. So, currenltly one has to choose between 'spiderfy' and 'update your markers properly' functionality). @lpongetti, any thoughts on this?
