### ISSUE TITLE
Make cluster calculation async (isolate).

### ISSUE THREAD

**Issue by Pepslee** [lpongetti/flutter_map_marker_cluster#139]
When cluster calculate a lot of markers (1000+) the Ui is blocking for a moment, because cluster calculation computes in the same thread. Is it possible to use isolate for cluster calculation ? to free Ui thread

**Comment by lpongetti** [comment]
it is possible, if you have some time you can try and add a pr if it works.
unfortunately I don't have much time to devote to it.
