### ISSUE TITLE
Impossible to add version 1.0.0

### ISSUE THREAD

**Issue by benbd5** [lpongetti/flutter_map_marker_cluster#140]
When I try: 
- to add in my pubsec.yaml:  flutter_map_marker_cluster: ^1.0.0

This error occurs: 
"last line of pub output: "So, because myapp depends on flutter_map_marker_cluster ^1.0.0, version solving failed."

When I try: `flutter pub add flutter_map_marker_cluster`
The version added is : flutter_map_marker_cluster: ^0.5.4

How can I use the version 1.0.0 ?

**Comment by lpongetti** [comment]
you have some conflict with other dependencies
