### ISSUE TITLE
MarkerTapBehavior.togglePopupAndHideRest doesnt work as expected

### ISSUE THREAD

**Issue by Pepslee** [lpongetti/flutter_map_marker_cluster#142]
Hi.
`MarkerTapBehavior.togglePopupAndHideRest` doesnt work as expected.
When I tap to the Marker popUp is appear, but when I tap one more time to that marker, popUp doesnt dissapear.

`popupState.selectedMarkers` is always empty and `contains(marker)` is always return false

This was tested for the example code of the flutter_map_marker_cluster

**Comment by blablabla123-cell** [comment]
The same issue. The same marker to be hidden is expected behaviour. hm

**Comment by rorystephenson** [comment]
Have you tried an older version to determine when this bug may have been introduced?
