### ISSUE TITLE
Is marker clustered?

### ISSUE THREAD

**Issue by Apollo108** [lpongetti/flutter_map_marker_cluster#149]
Hi, how can I understand if a certain marker is currently in a cluster? If I'm not mistaken, it was the 'isMarkerClustered' method before, but now it's a problem...

**Comment by Apollo108** [comment]
Speaking of workarounds, I know, there is the 'onMarkersClustered' callback, but it works only when markers are clustered, so I can't know, when a marker is unclustered...

**Comment by Apollo108** [comment]
Greetings! It would be nice to have any update on this issue, even if you don't plan to fix it)

**Comment by Apollo108** [comment]
Still waiting...

**Comment by Apollo108** [comment]
hey, ay updates here?

**Comment by jpgorganizer** [comment]
oh, I'm looking for that.
`onMarkersClustered `doesn't fire - why?
