### ISSUE TITLE
Spiderfied markers collapse after each update (if a new list of markers is passed every time)

### ISSUE THREAD

**Issue by Apollo108** [lpongetti/flutter_map_marker_cluster#150]
Well, not perfectly fine. It redraws markers, indeed, but it doesn't maintain it's state. In fact, when a cluster is spiderfied (open), and update happens, it collapses back, which makes it unusable (in case your markers are located on the same spot). So, currently one has to choose between 'spiderfy' and 'update your markers properly' functionality). @lpongetti, any thoughts on this?
![image](https://user-images.githubusercontent.com/16933202/211788889-2fdc4278-6db4-453f-ac33-c3126cf500bb.png)

_Originally posted by @Apollo108 in https://github.com/lpongetti/flutter_map_marker_cluster/issues/137#issuecomment-1378565018_

**Comment by Apollo108** [comment]
@lpongetti, this issue seems to be critical, no? Any help will be appreciated, and thank you for the awesome plugin, btw)

**Comment by Apollo108** [comment]
Greetings! It would be nice to have any update on this issue, even if you don't plan to fix it)

**Comment by Apollo108** [comment]
Still need an answer...

**Comment by Apollo108** [comment]
hey, ay updates here?

**Comment by Apollo108** [comment]
Please, reopen this issue and solve it, if possible

**Comment by linhlc-agiletech** [comment]
Hi @lpongetti, I have the same issue. Can you make it so that it keep spiderfy redraws markers?

**Comment by DevTello** [comment]
@lpongetti, the issue seems to be still there, any updates on it?
