### ISSUE TITLE
Migrate to flutter_map 5.0.0

### ISSUE THREAD

**Issue by slava-vl** [lpongetti/flutter_map_marker_cluster#167]
Because flutter_map_marker_cluster 1.1.1 depends on flutter_map ^4.0.0 and no versions of flutter_map_marker_cluster match >1.1.1 <2.0.0, flutter_map_marker_cluster ^1.1.1 requires flutter_map ^4.0.0.
So, because this app depends on both flutter_map ^5.0.0 and flutter_map_marker_cluster ^1.1.1, version solving failed.

**Comment by NeroThroN** [comment]
`flutter_map_marker_popup` has migrate to flutter_map 5.0.0 !

**Comment by Mmisiek** [comment]
Any chances to get update to Map 5.0 ?

**Comment by andreystavitsky** [comment]
please test [my pull request](https://github.com/lpongetti/flutter_map_marker_cluster/pull/173)

**Comment by xVemu** [comment]
> The 'problem' here is the `flutter_map_marker_popup` that this package depends on, which needs to be updated first.

It is up-to-date.

**Comment by starshipcoder** [comment]
Any news ?

**Comment by fvisticot** [comment]
please help

**Comment by aelahmartree** [comment]
Any help on this please?

**Comment by faccio02** [comment]
still issue

**Comment by andreystavitsky** [comment]
Finally it's resolved
