### ISSUE TITLE
Update dependency latlong2 to latest version

### ISSUE THREAD

**Issue by jonneroni** [lpongetti/flutter_map_marker_cluster#178]
`Because flutter_map_marker_cluster 1.1.1 depends on latlong2 ^0.8.1 and no versions of flutter_map_marker_cluster match >1.1.1 <2.0.0, flutter_map_marker_cluster ^1.1.1 requires latlong2 ^0.8.1.
So, because this app depends on both latlong2 ^0.9.0 and flutter_map_marker_cluster ^1.1.1, version solving failed.`

Fix: Update latlong2 from ^0.8.1 to ^0.9.0

**Comment by slava-vl** [comment]
it's already solved([migrate to flutter_map v5 #173](https://github.com/lpongetti/flutter_map_marker_cluster/pull/173)), but we are waiting for an updated version to be available
