### ISSUE TITLE
Popups not showing in iOS17

### ISSUE THREAD

**Issue by W2NJL** [lpongetti/flutter_map_marker_cluster#179]
Wondering if anyone else has encountered this issue.

I'm running version 1.2.0 (though this was happening with 1.1.2) and flutter_map 5.0.

I upgraded my environment to iOS 17 today.  

In PopUpOptions, the markerTapBehavior of:

 ```
 markerTapBehavior: MarkerTapBehavior.custom(
                    (marker, popUpState, popupController) => {

                      print('Whats the state?'),

         


                  popupController.togglePopup(marker.marker)
```

Or simply just using _markerTapBehavior: MarkerTapBehavior.togglePopup()_, produces no Popup.  The map pans over to the marker, but does nothing else.  The print statement I have in the custom marker behavior does get printed.

**Comment by Juggler98** [comment]
I'm also facing this issue on Android 11.
