### ISSUE TITLE
FM v6 is coming soon

### ISSUE THREAD

**Issue by JaffaKetchup** [lpongetti/flutter_map_marker_cluster#183]
The next version of flutter_map is coming soon, with breaking changes for all users and plugins!

Expected CHANGELOG: https://github.com/fleaflet/flutter_map/blob/release-prep/CHANGELOG.md
Likely to be merged PR with significant impacts: fleaflet/flutter_map#1615
Release prep PR: fleaflet/flutter_map#1632
New documentation (path liable to change): https://docs.fleaflet.dev/v/v6-1
Expected migration instructions, suitable for most users: https://docs.fleaflet.dev/v/v6-1/getting-started/migrating-to-v6
List of commits since v5 (more to come): https://github.com/fleaflet/flutter_map/compare/v5.0.0...master

**Comment by NeroThroN** [comment]
The version 6.0.0 has just been released. ([release note](https://github.com/fleaflet/flutter_map/releases/tag/v6.0.0))
