### ISSUE TITLE
Regular marker appearing animation

### ISSUE THREAD

**Issue by atoruliahotshotslabs** [lpongetti/flutter_map_marker_cluster#187]
Hey, first off, I just want to mention that this package is absolutely amazing. However, I have a particular question in mind. Is there a way in this package to animate the appearance of regular markers? Specifically, I'd love to achieve an effect where a standard marker, when appearing on the map from off-screen, has an entrance animation. If that's possible, could you provide some guidance on how best to accomplish this using your library?

**Comment by lpongetti** [comment]
hi, it's not possible at the moment, but feel free to add a pr to this project
