### ISSUE TITLE
Pie chart cluster markers

### ISSUE THREAD

**Issue by 926** [lpongetti/flutter_map_marker_cluster#19]
/enhancement 

Spent a couple of days trying to implement this, but failed

![pie-chart-clustering](https://user-images.githubusercontent.com/14161798/65601608-a821e380-dfa2-11e9-96e2-25f264fcd344.gif)

Any guidelines ?

**Comment by 926** [comment]
![Capture d’écran 2019-09-25 à 15 14 25](https://user-images.githubusercontent.com/14161798/65604177-457f1680-dfa7-11e9-923d-9095eaa98862.png)

**Comment by lpongetti** [comment]
it seems that it works

**Comment by lpongetti** [comment]
i have to see the source code

**Comment by 926** [comment]
Hi,
We use the map to know how much product remains in stock in different areas,
The figure displays the number of shops clustered,

Three colours : 

- grey :  no recent info / sync
- blue : stock ok
- orange : out of stock

we use last updateStatusDate to check if shop synced recently,
we use  a bool outOfStock to check it shop is out of stock,

Code sharing on this project is restricted by NDA (non disclosure agreement),
I would need more info and require that you also sign one, where can I PM you ?
