### ISSUE TITLE
Markers moving around map (when pinching/rotating) since updating to 1.3.0

### ISSUE THREAD

**Issue by jfmlima** [lpongetti/flutter_map_marker_cluster#190]
Since updating to the new version, both here and in flutter_map I get the behavior as represented in the recording.
Has anyone faced this issue so far? I might have missed some new configuration though...

https://github.com/lpongetti/flutter_map_marker_cluster/assets/5619521/6b281a04-18d4-4b9f-84c2-4e727068b6ca

**Comment by MaxiStefan** [comment]
Hey, I am facing the same issue and I almost exactly copy pasted my configuration from 0.4.3 to 1.3.0. I was about to go swooping through the migration for FM V6 to see how much has changed but haven't got the chance yet.

**Comment by altotunchitoo** [comment]
I think it comes from flutter_map replacing anchor with alignment.
I'm not so sure, the alignment is needed to reverse in order to use in the marker cluster code.

**Comment by jfmlima** [comment]
Confirmed that this affects the example as well.
@lpongetti can we have your insights here, please? 🙏 
I can try and dig into the codebase, but I have zero context on both packages 😕

**Comment by shrijanRegmi** [comment]
It was working fine in `flutter_map: ^6.0.0-dev.3`. I think this issue started occurring after `flutter_map` removed `anchorPos` in  `flutter_map: ^6.0.0`.

**Comment by shrijanRegmi** [comment]
Fixed this and sent a PR #193

**Comment by jfmlima** [comment]
Thanks @shrijanRegmi! How did you figure out that was the issue?

**Comment by shrijanRegmi** [comment]
> Thanks @shrijanRegmi! How did you figure out that was the issue?

@jfmlima  I spent lots of hours debugging the issue but nothing helped until I looked into the `flutter_map` commits and found out about `MobileLayerTransformer` which was missing in our case.
