### ISSUE TITLE
[Request] `selectedMarkerBuilder` support

### ISSUE THREAD

**Issue by kirpit** [lpongetti/flutter_map_marker_cluster#191]
This is a great package, thank you for creating it! I've just implemented it on top of already working `flutter_map_marker_popup` project and seems like all of my existing the features are working, except the `selectedMarkerBuilder` functionality.

Initially, I thought it should be easy just to pass that parameter too but when I dug into source code, I can see you're using [PopupLayer](https://pub.dev/documentation/flutter_map_marker_popup/latest/flutter_map_marker_popup.extension_api/PopupLayer-class.html) and not the [PopupMarkerLayer](https://pub.dev/documentation/flutter_map_marker_popup/latest/flutter_map_marker_popup/PopupMarkerLayer-class.html) class, where this param is implemented. `PopupMarkerLayer` also doesn't come from the marker_popup's "extension api" domain so I don't know what would be the impact of switching to it. Happy to help but simply confused over there.

**Comment by BearnLee** [comment]
I also have the same requirement. When expanding the markers, I want to highlight a single marker when clicking on it. Does the author have a support plan
