### ISSUE TITLE
using flutter_map from git using this plugin

### ISSUE THREAD

**Issue by thorizer** [lpongetti/flutter_map_marker_cluster#195]
Because flutter_map_marker_cluster >=1.3.0 depends on flutter_map from hosted and ngi_gps depends on flutter_map from git, flutter_map_marker_cluster >=1.3.0 is forbidden.
So, because ngi_gps depends on flutter_map_marker_cluster ^1.3.1, version solving failed.
exit code 1

**Comment by lpongetti** [comment]
Why depends on flutter_map from git?

**Comment by thorizer** [comment]
you can close this issue, i made a little fork and i wanted to use this plugin, what i did is also fork this plugin
