### ISSUE TITLE
MapOptions.minZoom required

### ISSUE THREAD

**Issue by MichalMisiaszek** [lpongetti/flutter_map_marker_cluster#2]
The plugin fails if minZoom/maxZoom are not defined in MapOptions as defaults are null. Without plugin map works fine.
```
_MarkerClusterGroupLayerState.initState
package:flutter_map_marker_cluster/src/marker_cluster.dart:720
StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:3846
ComponentElement.mount
package:flutter/…/widgets/framework.dart:3717
Element.inflateWidget
package:flutter/…/widgets/framework.dart:2961
MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:4982
Element.inflateWidget
package:flutter/…/widgets/framework.dart:2961
```

**Comment by MichalMisiaszek** [comment]
Shall I give it a go ? I see you changed API ?

**Comment by lpongetti** [comment]
0.1.4 is up now, if you want you can test!
thanks for your time

**Comment by MichalMisiaszek** [comment]
Is setState solved too ?

**Comment by lpongetti** [comment]
Yes

**Comment by MichalMisiaszek** [comment]
Are you sure about change of `MarkerClusterGroupLayerOptions` to `MarkerClusterLayerOptions` ?
The code does not compile and Readme is mixing both in description and example.

**Comment by MichalMisiaszek** [comment]
It seems like my project problem. The example works.
