### ISSUE TITLE
Update flutter_map dependency

### ISSUE THREAD

**Issue by TheManuz** [lpongetti/flutter_map_marker_cluster#218]
This package is preventing `flutter_map` update because it depends on `6.0.0`.

```zsh
Resolving dependencies...
Because flutter_map_marker_cluster 1.3.6 depends on flutter_map ^6.0.0 and <my_app> depends on flutter_map 7.0.1, flutter_map_marker_cluster 1.3.6 is forbidden.
So, because <my_app> depends on flutter_map_marker_cluster 1.3.6, version solving failed.
```

Can you please update flutter_map dependency?

**Comment by jannisnikoy** [comment]
@TheManuz There is a pull request open for this that was being blocked by another dependency, which has since been resolved. Fingers crossed for the PR to be merged soon 🙏

**Comment by bverhagen** [comment]
My users experience https://github.com/fleaflet/flutter_map/issues/1698 regularly, so being able to upgrade to flutter_map v7 would be great! Unfortunately, the issue above blocks me from doing so. It would be great if this gets merged and released soon 🙏

**Comment by thorito** [comment]
Do we know when the update will be available?

**Comment by PikPakPik** [comment]
If you want i fork with update https://github.com/PikPakPik/flutter_map_marker_cluster_2

**Comment by kenflannery** [comment]
> If you want i fork with update https://github.com/PikPakPik/flutter_map_marker_cluster_2

Thanks for doing that! Just installed it, glad to have v7 working now. I did notice that now when I click the cluster there's a temporary green polygon connecting the markers as it zooms in that wasn't happening in my previous version, but maybe that's normal and a simple showPolygon: false fixed the issue for me. Cheers!

**Comment by PikPakPik** [comment]
UP

**Comment by PikPakPik** [comment]
Remove stale label

**Comment by PikPakPik** [comment]
> Hi @lpongetti Could you please accept the flutter_map 7 upgrade PR?

https://pub.dev/packages/flutter_map_marker_cluster_2
