### ISSUE TITLE
Animation for Flutter map move

### ISSUE THREAD

**Issue by AmazingBite** [lpongetti/flutter_map_marker_cluster#23]
It'll be great if we could replace the .move function of Flutter map to our own animation. 
When we click on markers, it move just too fast, the tiles don't have time to load and when it finish, you don't really know where you are.

Threre is an exemple of this in Flutter map (https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart).

**Comment by lpongetti** [comment]
I can only expose a parameter for change the duration and the curve of the animation

**Comment by AmazingBite** [comment]
Thanks!
Personally I don't need anything else, but  the more we have, the best it is ^^.
