### ISSUE TITLE
Upgrade for the published package is required

### ISSUE THREAD

**Issue by Dev-Owl** [lpongetti/flutter_map_marker_cluster#25]
Hi,
It would be nice if you could publish an update to pub.dev to use the latest flutter_map (time of this post 0.8.0) to make sure you can use this great plugin with the latest Flutter version.
I cloned the master branch and checked for errors, local on my side all is working withe the latest version of flutter_map and Flutter.
Simply changed the pubspec.yaml for the lib and example to:
` flutter_map: ^0.8.0 
  latlong: ^0.6.1`

**Comment by kleeb** [comment]
merge to master would be a nice to have

**Comment by Dev-Owl** [comment]
Done, just send the changes.
