### ISSUE TITLE
Child class of Marker not supported.

### ISSUE THREAD

**Issue by MichalMisiaszek** [lpongetti/flutter_map_marker_cluster#3]
I am using my own Marker class which extends Marker from Flutter Map.
When I pass this Marker to map it works just fine.
If I pass the same list to cluster plugin it shows nothing.
Is this expected ? I would imagine that extensions of Marker class should work ?

**Comment by lpongetti** [comment]
Yes, In my project i'm using extensions of Marker and it works. Maybe you have a wrong builder in markerclusteroptions. So you have to see a cluster but it is only a container invisible.. i dont know, if you can post some code i'll help you better

**Comment by MichalMisiaszek** [comment]
I think this was not an issue, I added my class to the example code and markers were displayed just fine. The grouping does not work from other reason #4 . I am closing this one.
