### ISSUE TITLE
markers is not state?

### ISSUE THREAD

**Issue by mattia-lau** [lpongetti/flutter_map_marker_cluster#30]
i'm trying to call restful api to get the marker lat lng. However, when i set the new markers state. The map have no update. I'm also using user_location plugin

**Comment by lonewsk** [comment]
Same problem here.
I can update my markers list and they'll show up on the map without the Marker Cluster plugin.

But they won't through the marker cluster plugin.

**Comment by lonewsk** [comment]
Seems like somebody had the same problem here #4

**Comment by lonewsk** [comment]
Okay, got it running.
AFAIK, seems like the ClusterMarker plugin handles markers as references. So when you update your marker list or markers inside it, the object didn't changed.

I now call `markers = List.from(markers);` everytime I update my marker list. I also use this inside a setState() function.

It's working now. I hope doing that is not too CPU-intensive if I have too many markers.
