### ISSUE TITLE
Is there a way I can use this plugin with GoolgeMap instead of Flutter Map?

### ISSUE THREAD

**Issue by GreyOakSoftware** [lpongetti/flutter_map_marker_cluster#36]
Hi, I do realize that this plugin utilizes the flutter maps plugin, but is there any way I can use the plugin with the GoogleMaps plugin for flutter?

**Comment by cosmotek** [comment]
I think it's safe too assume no. This flutter_map component renders things in a completely different manner than the Google Map component. There's not really any way to make the two compatible as the Google Map component is a natively rendered widget, whereas this is a pure flutter component that renders tile images from a web-based source.
