### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by andreystavitsky** [lpongetti/flutter_map_marker_cluster#38]
`flutter_map_marker_cluster >=0.2.6 depends on flutter_map ^0.8.2 and AppName depends on flutter_map ^0.9.0, flutter_map_marker_cluster >=0.2.6 is forbidden`

**Comment by devzom** [comment]
up up

**Comment by gmaxferr** [comment]
plz update dependencies

**Comment by Allenisme** [comment]
plz update dependencies
