### ISSUE TITLE
setState not supported

### ISSUE THREAD

**Issue by MichalMisiaszek** [lpongetti/flutter_map_marker_cluster#4]
I want to refresh map and groupings with dynamic list of markers.
The grouping works only first time, if list is empty then updated and setState called map does not refresh. This obviously works on regular map. I attach modified example main to show the problem.

[main.dart.txt](https://github.com/lpongetti/flutter_map_marker_cluster/files/3293833/main.dart.txt)

**Comment by lpongetti** [comment]
I will try

**Comment by MichalMisiaszek** [comment]
> I will try

Just use the main.dart I included and you will understand what I mean. Maybe I am doing something wrong but I doubt. On setState after button push the markers array is populated but map does not refresh. Otherwise it seems like great plugin.

**Comment by MichalMisiaszek** [comment]
Yes it is fixed. Thanks !

**Comment by topnax** [comment]
@MichalMisiaszek does it work for you now? I am currently having the same issue as you.

**Comment by topnax** [comment]
The new overridden method `didUpdateWidget` gets called but does not do anything because `listEquals(_markers, options.markers)` returns true. How can I update `options.markers`?

**Comment by lpongetti** [comment]
ok i understand all, i will try to fix this issue.. the probles is that list and marker are by reference. so if you change marker's position for dart the list is not changed

**Comment by lpongetti** [comment]
i dont know how to fix this at the moment.. however you can bypass it by recreating all the markers with the new position

**Comment by MichalMisiaszek** [comment]
So I am recreating list in 'build' method on each set State. This works for me.

**Comment by lpongetti** [comment]
@topnax @MichalMisiaszek 
issue fixed in 0.1.5
i added an example of state management with this plugin.
If you recreate the list it's perfect but if you change only one marker in the list you have to insert this:
`` `
markers = List.from (markers);
`` `
this create a copy of list and change memory cells's pointers so I can see if there's a change without performance problem

Thanks

**Comment by Apollo108** [comment]
> @topnax @MichalMisiaszek issue fixed in 0.1.5 i added an example of state management with this plugin. If you recreate the list it's perfect but if you change only one marker in the list you have to insert this: `` ` markers = List.from (markers); `` ` this create a copy of list and change memory cells's pointers so I can see if there's a change without performance problem
> 
> Thanks

this brings another problem with losing spiderfy state, see [https://github.com/lpongetti/flutter_map_marker_cluster/issues/150](url)
