### ISSUE TITLE
Callback functions for single<->cluster marker events

### ISSUE THREAD

**Issue by aytunch** [lpongetti/flutter_map_marker_cluster#41]
onMarkersAddedToCluster(List<Marker> markers, Cluster cluster)
onMarkersRemovedFromCluster(List<Marker> markers, Cluster cluster)
onClustersCombined(List<Cluster> input_clusters, Cluster combined_cluster)
onClusterBreak(Cluster big_source_cluster, List<Cluster> small_dest_clusters, List<Marker> dest_markers)

I realized even trying to come up with an api overview is hard, but it would definitely be useful if we had these kind of callbacks.

**Comment by RanfiCD** [comment]
I'm currently trying to draw polylines under both the cluster markers and the normal markers, but I'm struggling to come up with a solution without having access to the clusters location.

Like @aytunch I too think that it would be nice to have an API for that. In my case, I would like something like this:

**onLayerUpdated(List< MarkerClusterNode > clusters, List< MarkerNode > markers);**

That way we would have a snapshot of the nodes and all their info.

**Comment by HugoHeneault** [comment]
This have been closed without further details. Is there now a way to listen to cluster events?
