### ISSUE TITLE
Slow cluster calculation

### ISSUE THREAD

**Issue by yakanet** [lpongetti/flutter_map_marker_cluster#45]
Hi,

I'm in the case where I have 6000+ markers on my map. I give the user the possibility of filter those markers (with some pre-defined filters). 

The issue is each time I change my filter, there is a recalcultation for the cluster and it create a UI freeze. 
It is possibile to have this recalculation in a async way ? Or do the recalculation to inside another Thread than the UI Thread ?

**Comment by jiazeh** [comment]
I have the same issue.

**Comment by yakanet** [comment]
Manage to partially solve this issue with #52 
There is less freeze, but the app is still freezing during the cluster computation.

**Comment by ShellsOfSilver** [comment]
@yakanet this can reduce the number of friezes - https://github.com/lpongetti/flutter_map_marker_cluster/pull/53

**Comment by ShellsOfSilver** [comment]
@yakanet @jiazeh I hope this solution helps solve freeze problems - https://github.com/lpongetti/flutter_map_marker_cluster/pull/54

**Comment by yakanet** [comment]
@ShellsOfSilver thank you for your help, unfortunately there is not so much improvements.
I monitor with flutter performance the change from your PR (20 000 markers on the map, but only 3 visibles).

## Without the change
![flutter_map_cluster_before](https://user-images.githubusercontent.com/1936518/93068172-6c34d200-f67c-11ea-8cbe-ac013db2a20a.png)

## After the change
![flutter_map_cluster_after](https://user-images.githubusercontent.com/1936518/93068173-6ccd6880-f67c-11ea-8eef-674e47b13afe.png)

It seems your change spent more time in the rebuild step (compare to the didUpdateWidget) due to the `contains` method from the LatLngBounds class.

**Comment by jiazeh** [comment]
@yakanet @ShellsOfSilver I found that the problem for the slow cluster calculation is the **button**. When I change FAB to image.assets the problem was solved. But my problem is that the picture must have each diff text..
```
MarkerClusterLayerOptions(
...
builder: (context, markers) {
     return Image.asset(circleIcon);
  }
)
```

**Comment by lpongetti** [comment]
has anyone tried using Isolate?
