### ISSUE TITLE
Improvement request.

### ISSUE THREAD

**Issue by MichalMisiaszek** [lpongetti/flutter_map_marker_cluster#5]
My markers have diffrent types (icons, colors and dedicated type field). At the moment they are all grouped together. How about customization of grouping marker ? I remember once seeing grouping marker with a colorful circle around with sections depending on amount of specific markers. I can't find this example now. Also Leaflet allows for customized group marker (which could help achieve this result).
Any suggestions ?
Thnanks for great plugin !

**Comment by lpongetti** [comment]
In markerclusterlayeroption you have a builder. You can insert conditions and return different cluster

**Comment by MichalMisiaszek** [comment]
Yes I noticed it, working on it. BTW. when I pass diffrent list on each pass will it refresh ? I have some problems.

**Comment by lpongetti** [comment]
Yes, everytime that plugin draw a cluster, builder will be called.

**Comment by MichalMisiaszek** [comment]
Somehow I have problem with it suddenly.  I create copy of list inside build and somehow plugin does not call build at all.

**Comment by lpongetti** [comment]
I dont know how to help you. Can do you post your code?

**Comment by MichalMisiaszek** [comment]
I will try to update example, give me few minutes.

**Comment by MichalMisiaszek** [comment]
Is this yours debug message ?
```/ViewRootImpl@9899862[MainActivity](29845): ViewPostIme pointer 1
D/ViewRootImpl@9899862[MainActivity](29845): ViewPostIme pointer 0
D/ViewRootImpl@9899862[MainActivity](29845): ViewPostIme pointer 1
D/ViewRootImpl@9899862[MainActivity](29845): ViewPostIme pointer 0```

**Comment by lpongetti** [comment]
No

**Comment by MichalMisiaszek** [comment]
Check this file with 2 buttons adding in dynamic way and it shows nothing.
[main.dart.txt](https://github.com/lpongetti/flutter_map_marker_cluster/files/3299940/main.dart.txt)

**Comment by MichalMisiaszek** [comment]
Ok, I found solution, `_markersList` must be declared as member of class not inside `build` method.

**Comment by lpongetti** [comment]
Try to not use setstate with global variable

**Comment by MichalMisiaszek** [comment]
If I tap on group marker when it map is not maxZoom it will zoom out instead of zoom in. Aby idea why ?

**Comment by lpongetti** [comment]
Maybe wrong settings

**Comment by MichalMisiaszek** [comment]
Which one ?

**Comment by lpongetti** [comment]
i dont know, i never seen this issue. You have to discover it

**Comment by lpongetti** [comment]
ok i understand all, i will try to fix this issue
