### ISSUE TITLE
Flutter button to new page

### ISSUE THREAD

**Issue by randomkcanguy** [lpongetti/flutter_map_marker_cluster#57]
When I have more than 1 cluster marker in view and click a button to go to a new page there will be this error "There are multiple heroes that share the same tag within a subtree." and the screen will go black

**Comment by lpongetti** [comment]
don't use FloatingActionButton if you have more than one page but another widget (custom maybe)

**Comment by randomkcanguy** [comment]
Im not using a floating action button but a custom appbar with iconbutton
