### ISSUE TITLE
BUILD FAILED 

### ISSUE THREAD

**Issue by 926** [lpongetti/flutter_map_marker_cluster#6]
Hi @lpongetti 

I get a build failed when running the example : 

It seems to come from the gradle.
Sorry if this is very newbie issue. Any clues ?

packages/flutter_tools/gradle/flutter.gradle' line: 665
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileflutterBuildDebugArm'.

I also get compiler alert from the mbtiles_image_provider.dart:93:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' 
Here is a full capture :
![image](https://user-images.githubusercontent.com/14161798/59872467-4fcabc80-9389-11e9-8253-3b0eba1a42d7.png)

**Comment by lpongetti** [comment]
Run flutter doctor please

**Comment by lpongetti** [comment]
Flutter channel have to be 'stable'
