### ISSUE TITLE
Extrude user location plugin from clustering

### ISSUE THREAD

**Issue by DonWasyl** [lpongetti/flutter_map_marker_cluster#66]
Is there any possibility to use both plugins (`flutter_map_marker_cluster` and `user_location_plugin` together? Now user location is clustered. (when I put `userLocationOptions` below `MarkerClusterLayerOption` then location disappeared :(

```
userLocationOptions = UserLocationOptions(
      [...]
      markers: markers,
      [...]
    );
```
```
FlutterMap(
      mapController: mapController,
      options: new MapOptions(
        [...]
        plugins: [
          UserLocationPlugin(),
          MarkerClusterPlugin(),
        ],
        [...]
      ),
      layers: [
        new TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
        ),
        userLocationOptions,
        MarkerClusterLayerOptions(
          [...]
          markers: markers,
          [...]
          },
        ),
      ],
    );
```

**Comment by gabrieletelesca** [comment]
`MarkerClusterLayerOptions(
          [...]
          markers: markers,
          [...]
          },
        )`
        
`markers` must not include the Marker representing the user current location of the user, otherwise it will cluster it like all the other ones in the `markers` list
