### ISSUE TITLE
Working version for flutter_map 0.6.1+2

### ISSUE THREAD

**Issue by ZeBrody** [lpongetti/flutter_map_marker_cluster#8]
Hello, i adapted your plugin to work with the beta channel version of flutter_map (0.6.1+2). Are you interested in creating a branch of master where i can pr my changes?

**Comment by ZeBrody** [comment]
Sorry, i just noticed, that the latest version of flutter_map has not been released on pub yet, so it will only work when using the git version as dependency.

**Comment by lpongetti** [comment]
branch develop
