### ISSUE TITLE
Spider not working ?

### ISSUE THREAD

**Issue by Mmisiek** [lpongetti/flutter_map_marker_cluster#92]
Hello,
I have used this great plugin in my app 2 years ago, I customized it a little and now I don't remember how but I will figure it out. Anyway I updated my app to the newest official version 0.4.0 and I can't make spiders work.
Basically I zoom in until I get cluster button and with number of markers below it but when I touch it, it will not split and create spider with markers away. Here is my configuration: 
` MarkerClusterLayerOptions(
                    maxClusterRadius: _buttonSize.toInt(),
                    size: Size(_buttonSize, _buttonSize),
                    spiderfyCircleRadius: 80,
                    zoomToBoundsOnClick: false,
                    spiderfySpiralDistanceMultiplier: 2,
                    circleSpiralSwitchover: 12,
                    fitBoundsOptions: FitBoundsOptions(
                      padding: EdgeInsets.all(5),
                    ),
                    markers: _markersList,
                    showPolygon: true,
                    polygonOptions: PolygonOptions(
                        borderColor: Colors.blueAccent,
                        color: Colors.black12,
                        borderStrokeWidth: 3),
                    builder: (context, markers) {
                      return FloatingActionButton(
                        child: Text(markers.length.toString()),
                        onPressed: null,
                      );
                    },
                  )`
What am I missing ?
This great plugin and great work !
Thanks
Michal

**Comment by lpongetti** [comment]
i tried with version 0.4.3 and it works perfectly
