### ISSUE TITLE
Loose marker alignment after upgrading library

### ISSUE THREAD

**Issue by sm2017** [lpongetti/flutter_map_marker_cluster#98]
I upgraded `flutter_map_marker_cluster` from `0.4.0` to `0.4.2` and `anchorPos: AnchorPos.align(AnchorAlign.top)` it not working anymore and changing it is not affected

In the `0.4.0` the marker and popup aligned nicely, the popup is opened right above the marker, in `0.4.2` position of popup is ok but the marker position has gone down a bit and we have a gap between marker and popup

**Comment by lpongetti** [comment]
ok tnx

**Comment by lpongetti** [comment]
pls try v0.4.3

**Comment by lpongetti** [comment]
now it works again, sorry for the inconvenience

**Comment by sm2017** [comment]
@lpongetti it's OK now, Thanks a lot
